AppBase/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', inicio, name="Inicio"),
    path('ag-pelicula', agregar_pelicula, name="AgregarPelicula"),
    path('l-peliculas', lista_peliculas, name="ListaPeliculas"),
    path('el-peliculas/<int:id>', eliminar_pelicula, name="EliminarPelicula"),
    path('ed-peliculas/<int:id>', editar_pelicula, name="EditarPelicula"),
    path('ag-resena', agregar_resena, name='AgregarResena'),
    path('l-resenas', lista_resenas, name='ListaResenas'),
    path('el-resenas/<int:id>', eliminar_resena, name="EliminarResena"),
    path('ed-resenas/<int:id>', editar_resena, name="EditarResena"),
    path('busq-pelicula', busqueda_peliculas, name="BusquedaPeliculas"),
    path('buscar-nombre', buscar_nombre, name="BuscarNombre"),
    path('buscar-genero', buscar_genero, name="BuscarGenero"),
    path('buscar-empresa', buscar_empresa, name="BuscarEmpresa"),
    path('buscar-valoracion', buscar_valoracion, name="BuscarValoracion"),
    path('about-me', AboutMe, name="AboutMe"),
    path('foro', lista_temas, name='Foro'),
    path('crear-tema', crear_tema, name='CrearTema'),
    path('ed-tema/<int:pk>', editar_tema, name='EditarTema'),
    path('el-tema/<int:pk>', eliminar_tema, name='EliminarTema'),
    path('foro/<int:pk>/', detalle_tema, name='DetalleTema'),
    path('<int:pk>/crear-coment', crear_comentario, name='CrearComentario'),
]

AppMensajes/urls.py
from django.urls import path
from .views import *

app_name = 'AppMensajes'

urlpatterns = [
    path('inbox', ConversacionListView.as_view(), name='Inbox'),
    path('nuevo-msj', ConversacionCreateView.as_view(), name='CrearConversacion'),
    path('<int:room_id>', ConversacionDetailView.as_view(), name='VerConversacion'),
    path('<int:pk>/agregar-msj/', AgregarMensajeConversacionView.as_view(), name='AgregarMensaje'),
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppBase.urls')),
    path('', include('AppRegistro.urls')),
    path('', include('AppLogin.urls')),
    path('', include('AppPerfiles.urls')),
    path('', include('AppMensajes.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppBase/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
GENERO_OPCIONES = [('accion', 'Acción'), ('aventura', 'Aventura'), ('cficcion', 'CFiccion'), ('comedia', 'Comedia'), ('comerciales', 'Comerciales'), 
                   ('deportes', 'Deportes'), ('documentales', 'Documentales'), ('drama', 'Drama'),('entrevistas', 'Entrevistas'), ('musica', 'Música'), 
                   ('suspenso', 'Suspenso'), ('terror', 'Terror'), ]

GENERO_OPCIONES = sorted(GENERO_OPCIONES, key=lambda x: x[1])

VALORACIONES_OPCIONES = [(i, str(i)) for i in range(1, 11)]

class Pelicula(models.Model):
    nombre = models.CharField(max_length=255)
    fecha_salida = models.DateField()
    genero = models.CharField(max_length=255, choices=GENERO_OPCIONES)
    empresa = models.CharField(max_length=255)
    descripcion = models.TextField()
    valoracion = models.IntegerField(choices=VALORACIONES_OPCIONES, null=False)
    def __str__(self):
        return f"{self.nombre} - {self.genero} - {self.empresa}"

class Resena(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    contenido = models.TextField()
    pelicula = models.ForeignKey(Pelicula, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.autor} - {self.pelicula.nombre}"

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)
    def __str__(self):
        return f"{self.user} / {self.imagen}"
    
class Tema(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.creador} - {self.titulo}"

class Comentario(models.Model):
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE, related_name='comentarios')
    def __str__(self):
        return f"{self.creador} - {self.tema}"

AppBase/forms.py
from django import forms
from .models import *

GENERO_OPCIONES = [('accion', 'Acción'), ('aventura', 'Aventura'), ('cficcion', 'CFiccion'), ('comedia', 'Comedia'), ('comerciales', 'Comerciales'), 
                   ('deportes', 'Deportes'), ('documentales', 'Documentales'), ('drama', 'Drama'),('entrevistas', 'Entrevistas'), ('musica', 'Música'), 
                   ('suspenso', 'Suspenso'), ('terror', 'Terror'),]

GENERO_OPCIONES = sorted(GENERO_OPCIONES, key=lambda x: x[1])

VALORACIONES_OPCIONES = [(i, str(i)) for i in range(1, 11)]

class PeliculasForm(forms.Form):
    nombre = forms.CharField(max_length=255)
    fecha_salida = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    genero = forms.CharField(max_length=255, widget=forms.Select(choices=GENERO_OPCIONES))
    empresa = forms.CharField(max_length=255)
    descripcion = forms.CharField(max_length=255)
    valoracion = forms.IntegerField(required=True, widget=forms.Select(choices=VALORACIONES_OPCIONES))

class ResenaForm(forms.ModelForm):
    class Meta:
        model = Resena
        fields = ('__all__')

class BuscarNombre(forms.Form):
    nombre = forms.CharField(label='Nombre de la pelicula', max_length=255)

class BuscarGenero(forms.Form):
    genero = forms.CharField(label='Nombre del género', max_length=255, widget=forms.Select(choices=GENERO_OPCIONES))

class BuscarEmpresa(forms.Form):
    empresa = forms.CharField(label='Nombre de la empresa', max_length=255)

class BuscarValoracion(forms.Form):
    valoracion = forms.IntegerField(label='Valoracion', widget=forms.Select(choices=VALORACIONES_OPCIONES))

class TemaForm(forms.ModelForm):
    class Meta:
        model = Tema
        fields = ['titulo', 'descripcion']

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']

AppBase/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import *
from .forms import *

# Create your views here.
def inicio(request):
    try: 
        avatar = Avatar.objects.get(user=request.user.id)
        return render(request, 'inicio.html', {'url': avatar.imagen.url})
    except:
        return render(request, "inicio.html")
    
def AboutMe(request):
    return render(request, "aboutme.html")
    
#1er Círculo Inicio!!
@login_required   
def agregar_pelicula(request):
    if request.method == 'POST':
        mi_formulario = PeliculasForm(request.POST)
        if mi_formulario.is_valid():
            data = mi_formulario.cleaned_data
            pelicula = Pelicula(nombre=request.POST['nombre'], fecha_salida=request.POST['fecha_salida'], genero=request.POST['genero'], empresa=request.POST['empresa'], descripcion=request.POST['descripcion'], valoracion=request.POST['valoracion'],)
            pelicula.save()
            return render(request, "inicio.html", {"mensaje": "Se ha agregado una pelicula"})
        else:
            return render(request, "inicio.html", {"mensaje": "Formulario invalido"})
    else:
        mi_formulario = PeliculasForm()
        return render(request, "agregar_pelicula.html", {"mi_formulario": mi_formulario})

@login_required  
def lista_peliculas(request):
    orden = request.GET.get('orden', None)
    peliculas = Pelicula.objects.all()
    if orden == 'lanzamiento':
        peliculas = peliculas.order_by('-fecha_salida')
    elif orden == 'valoracion':
        peliculas = peliculas.order_by('-valoracion')
    return render(request, "ver_peliculas.html", {"peliculas": peliculas})

@login_required
def eliminar_pelicula(request, id):
    if request.method == 'POST':
        pelicula = Pelicula.objects.get(id=id)
        pelicula.delete()
        pelicula = Pelicula.objects.all()
        return HttpResponseRedirect('/l-peliculas')

@login_required    
def editar_pelicula(request, id):
    pelicula = Pelicula.objects.get(id=id)
    if request.method == 'POST':
        mi_formulario = PeliculasForm(request.POST)
        if mi_formulario.is_valid():
            data = mi_formulario.cleaned_data
            pelicula.nombre = data['nombre']
            pelicula.fecha_salida = data['fecha_salida']
            pelicula.genero = data['genero']
            pelicula.empresa = data['empresa']
            pelicula.descripcion = data['descripcion']
            pelicula.valoracion = data['valoracion']
            pelicula.save()
            return render(request, "inicio.html", {"mensaje": "Cambios realizados"})
        else:
            return render(request, "inicio.html", {"mensaje": "Formulario invalido"})
    else:
        mi_formulario = PeliculasForm(initial={
            "nombre": pelicula.nombre,
            "fecha_salida": pelicula.fecha_salida,
            "genero": pelicula.genero,
            "empresa": pelicula.empresa,
            "descripcion": pelicula.descripcion,
            "valoracion": pelicula.valoracion
        })
        return render(request, "editar_peliculas.html", {"mi_formulario": mi_formulario, "id": pelicula.id})

@login_required    
def agregar_resena(request):
    mi_formulario = ResenaForm()
    if request.method == 'POST':
        mi_formulario = ResenaForm(request.POST)
        if mi_formulario.is_valid():
            mi_formulario.save()
            return HttpResponseRedirect('/l-resenas')
    return render(request, 'agregar_resena.html', {'mi_formulario': mi_formulario})

@login_required
def lista_resenas(request):
    resenas = Resena.objects.all()
    return render(request, 'lista_resenas.html', {'reseñas': resenas})

@login_required
def eliminar_resena(request, id):
    if request.method == 'POST':
        resena = Resena.objects.get(id=id)
        resena.delete()
        resena = Resena.objects.all()
        return HttpResponseRedirect('/l-resenas')

login_required    
def editar_resena(request, id):
    resena = Resena.objects.get(id=id)
    if request.method == 'POST':
        mi_formulario = ResenaForm(request.POST)
        if mi_formulario.is_valid():
            data = mi_formulario.cleaned_data
            resena.autor = data['autor']
            resena.contenido = data['contenido']
            resena.pelicula = data['pelicula']
            resena.save()
            return render(request, "inicio.html", {"mensaje": "Cambios realizados"})
        else:
            return render(request, "inicio.html", {"mensaje": "Formulario invalido"})
    else:
        mi_formulario = ResenaForm(initial={
            "autor": resena.autor,
            "contenido": resena.contenido,
            "pelicula": resena.pelicula,
        })
        return render(request, "editar_resena.html", {"mi_formulario": mi_formulario, "id": resena.id})
#1er Círculo Fin!!

#2do Círculo Inicio!!
@login_required
def busqueda_peliculas(request):
    return render(request, 'buscar_peliculas.html')

@login_required
def buscar_nombre(request):
    if request.method == 'GET':
        form = BuscarNombre(request.GET)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            peliculas = Pelicula.objects.filter(nombre__icontains=nombre)
            return render(request, 'res_busqueda_nombre.html', {'peliculas': peliculas, 'nombre': nombre})
    else:
        form = BuscarNombre()
    return render(request, 'busq_nombre.html', {'form': form})

@login_required
def buscar_genero(request):
    if request.method == 'GET':
        form = BuscarGenero(request.GET)
        if form.is_valid():
            genero = form.cleaned_data['genero']
            peliculas = Pelicula.objects.filter(genero__icontains=genero)
            return render(request, 'res_busqueda_genero.html', {'peliculas': peliculas, 'genero': genero})
    else:
        form = BuscarGenero()
    return render(request, 'busq_genero.html', {'form': form})

@login_required
def buscar_empresa(request):
    if request.method == 'GET':
        form = BuscarEmpresa(request.GET)
        if form.is_valid():
            empresa = form.cleaned_data['empresa']
            peliculas = Pelicula.objects.filter(empresa__icontains=empresa)
            return render(request, 'res_busqueda_empresa.html', {'peliculas': peliculas, 'empresa': empresa})
    else:
        form = BuscarEmpresa()
    return render(request, 'busq_empresa.html', {'form': form})

@login_required
def buscar_valoracion(request):
    if request.method == 'GET':
        form = BuscarValoracion(request.GET)
        if form.is_valid():
            valoracion = form.cleaned_data['valoracion']
            peliculas = Pelicula.objects.filter(valoracion__icontains=valoracion)
            return render(request, 'res_busqueda_valoracion.html', {'peliculas': peliculas, 'valoracion': valoracion})
    else:
        form = BuscarValoracion()
    return render(request, 'busq_valoracion.html', {'form': form})
#2do Cícurlo Final!!

#3er Círculo Inicio!!
@login_required
def lista_temas(request):
    temas = Tema.objects.all()
    return render(request, 'foro.html', {'temas': temas})

@login_required
def crear_tema(request):
    if request.method == 'POST':
        form = TemaForm(request.POST)
        if form.is_valid():
            tema = form.save(commit=False)
            tema.creador = request.user
            tema.save()
            return HttpResponseRedirect('/foro')
    else:
        form = TemaForm()
    return render(request, 'crear_tema.html', {'form': form})

@login_required
def editar_tema(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    if request.method == 'POST':
        form = TemaForm(request.POST, instance=tema)
        if form.is_valid():
            tema = form.save()
            return HttpResponseRedirect('/foro')
    else:
        form = TemaForm(instance=tema)
    return render(request, 'editar_tema.html', {'form': form, 'tema': tema})

@login_required
def eliminar_tema(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    tema.delete()
    return HttpResponseRedirect('/foro')

@login_required
def detalle_tema(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    comentarios = Comentario.objects.filter(tema=tema)
    form = ComentarioForm()
    return render(request, 'detalle_tema.html', {'tema': tema, 'comentarios': comentarios, 'form': form})

@login_required
def crear_comentario(request, pk):
    tema = get_object_or_404(Tema, pk=pk)
    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.creador = request.user
            comentario.tema = tema
            comentario.save()
            return HttpResponseRedirect(reverse('DetalleTema', args=[tema.pk]))
    else:
        form = ComentarioForm()
    return render(request, 'crear_comentario.html', {'form': form})
#3er Círculo Final

#El 4to Círculo está en AppMensajes

AppBase/templates/aboutme.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'css/aboutme.css' %}">
<div class="container" style="max-width: 80rem; ">
    <div class="card text-white bg-dark mb-3" style="max-width: 80rem; padding: 2rem; ">
        <h1 class="text-center" style="color: yellow;">Hola! Soy Sandra Quevedo</h1>
        <img class="center" height="400px" src="{% static 'css/foto cv.jpeg' %}" alt="Imagen saludo">
        <body>
            <p class="text-center" style="color: lemonchiffon;">Nací el 07 de noviembre 1970, soy de Rosario, Argentina,
                amante de los gatos, hincha ferviente de Boca Juniors y admiradora de Martin Palermo.</p>
            <p class="text-center" style="color: lemonchiffon">Soy Contadora Pública, y me especialicé en Costos y
                Gestión Empresarial y en Finanzas (Especialización y Maestria).</p>
            <p class="text-center" style="color: lemonchiffon;">Meses antes de comenzar la pandemia tomé la decisión de
                empezar a programar, considerando que además de ser afin a mi profesión, se iniciaba un gran y largo
                camino colmado de desafíos.</p>
            <p class="text-center" style="color: lemonchiffon;">Mi mayor deseo es crear mi propia aplicación orientada a
                la masa salarial de RRHH, dado que trabajo en una empresa del sector público en un area asociada a dicha 
                actividad.</p>
            <p class="text-center" style="color: lemonchiffon;">El objetivo es automatizar ciertas actividades que un
                sistema gestor de RRHH no contempla.</p>
            <p class="text-center" style="color: lemonchiffon;">Comencé en CoderHouse en abril del 2022 con los cursos
                de Desrrollo Web, JavaScript, ReactJs y React Native (Desarrollo de Aplicaciones).</p>
            <p class="text-center" style="color: lemonchiffon;">Actualmente estoy finalizando este curso de Python orientado 
                al desarrollo web en Coderhouse y luego continuar con programación R para más adelante encarar Data Science.</p>
            <p class="text-center" style="color: lemonchiffon;">A continuación, dejo el acceso a mi repositorio en GitHub, 
                donde se encuentran disponibles mis trabajos a la fecha...Agradezco tu tiempo aplicado a la lectura de estas 
                simples líneas....Estamos en contacto!!!</p>
            <div class="text-center" style="background-color: rgb(50, 49, 49);  padding: 2rem;">
                <div style="margin-top: 20px;">
                    <a href="https://github.com/Tincho2002" class="btn btn-outline-warning" target="_blank">Ir a
                        Github</a>
                </div>
                <div style="margin-top: 20px;">
                    {% url 'Inicio' as url %}
                    <a type="button" class="btn btn-outline-danger" onclick="window.location.href='{{ url }}'">Volver al Inicio</a>
                </div>
            </div>
        </body>
    </div>
</div>
{% endblock contenidoQCambia %}

AppBase/templates/agregar_resena.html
{% extends 'base.html' %}

{% load static %}

{% block contenidoQCambia %}
<link rel="stylesheet" type="text/css" href="{% static 'css/agregar_resena.css' %}">
<div class="container" style="max-width: 30rem;">
    <div class="card text-white bg-dark mb-3" style="max-width: 30rem; padding: 1rem; max-height: 35rem;">
        <h2 class="heading-black text-center" style="color: yellow;">Agregar Reseña</h2>
    <form method="POST" class="input-group-prepend" style="background-color: rgb(34, 33, 36);">{% csrf_token %}
        {{ mi_formulario.as_p }}
        <button type="submit" class="btn btn-outline-success">Agregar</button>
    </form>
    </div>
    </div>
{% endblock contenidoQCambia %}

AppBase/templates/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Knight - Free Bootstrap 4 Product Landing Page Template</title>
    <meta name="description" content="Knight is a beautiful Bootstrap 4 template for product landing pages." />

    <!--Inter UI font-->
    <link href="https://rsms.me/inter/inter-ui.css" rel="stylesheet">

    <!--vendors styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

    <!-- Bootstrap CSS / Color Scheme -->
    <link rel="stylesheet" href="{% static 'css/default.css'%}" id="theme-color">
</head>

<body>

    <!--navigation-->
    <section class="smart-scroll">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-dark">
                <a class="navbar-brand heading-black" style="color: yellow;" href="{% url 'Inicio' %}">
                    HOME
                </a>
                <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span data-feather="grid"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link page-scroll" style="color: yellow;" href="#features">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link page-scroll" style="color: yellow;" href="{% url 'AboutMe' %}">About
                                Me</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link page-scroll" style="color: yellow;" href="{% url 'Perfil' %}">Perfil</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link page-scroll" style="color: yellow;"
                                href="{% url 'AppMensajes:Inbox' %}">Mensajes</a>
                        </li>
                        {% endif %}
                        <li class="nav-item" style="color:lemonchiffon;">
                            {% if user.is_authenticated %}
                            {% if url %}
                            <img height="60px" src="{{url}}" alt="avatar">
                            {% endif %}
                            <p>Bienvenido {{user.username}}</p>
                            <a class="nav-link page-scroll d-flex flex-row align-items-center text-danger"
                                href="{% url 'Logout' %}">
                                <em data-feather="layout" width="18" height="18" class="mr-2" style="color: red;"></em>
                                LOGOUT
                            </a>
                            {% else %}
                            <a class="nav-link page-scroll d-flex flex-row align-items-center text-success"
                                href="{% url 'Login' %}">
                                <em data-feather="layout" width="18" height="18" class="mr-2"
                                    style="color: green;"></em>
                                LOGIN
                            </a>
                            {% endif %}
                        </li>

                    </ul>
                </div>
            </nav>
        </div>
    </section>
    {% if user.is_authenticated %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% endif %}
    <!--hero header-->
    {% if not user.is_authenticated %}
    <section class="py-7 py-md-0 bg-hero" id="home">
        <div class="container">
            <div class="row vh-md-100">
                <div class="col-md-8 col-sm-10 col-12 mx-auto my-auto text-center">
                    <img class="center" height="280rem" margin-top="10rem" src="{% static 'img/cine.jpeg' %}"
                        alt="Imagen cine">
                    <h1 class="heading-black text" style="color: yellow;">Bienvenido a Movie-Ok!</h1>
                    <p class="lead py-3" style="color: yellow;"> El Blog de películas que te permite ordenalas
                        cronológicamente, valoralas, reseñalas, comentalas en el foro o habla con tus amigos. Clickeá en
                        Features o scrolleá hacia abajo para acceder a lo que quieras.</p>
                    <a class="btn btn-outline-warning d-inline-flex flex-row align-items-center"
                        href="{% url 'RegistroUsuarios' %}">
                        CREAR USUARIO
                        <em class="ml-2" data-feather="arrow-right"></em>
                    </a>
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    <!-- features section -->
    {% block contenidoQCambia %}

    {% endblock contenidoQCambia %}

    <section class="pt-6 pb-7" id="features">
        <div class="container">
            <div class="row mt-5">
                <div class="col-md-10 mx-auto">
                    <div class="row feature-boxes">
                        <div class="col-md-6 box">
                            <div class="icon-box box-primary">
                                <a href="{% url 'ListaPeliculas' %}">
                                    <div class="icon-box-inner" style="color: yellow;">
                                        <span src="{% static 'img/analisis-de-los-datos.png' %}" data-feather="edit-3"
                                            width="35" height="35"></span>
                                    </div>
                            </div>
                            </a>
                            <h5 style="color: yellow;">Crea tus listas de peliculas favoritas</h5>
                            <p class="text-muted" style="color: yellow;">Acá vas a poder guardarlas, valorarlas,
                                ordenarlas y reseñarlas.</p>
                        </div>
                        <div class="col-md-6 box">
                            <div class="icon-box box-success">
                                <a href="{% url 'BusquedaPeliculas' %}">
                                    <div class="icon-box-inner" style="color: yellow;">
                                        <span data-feather="monitor" width="35" height="35"></span>
                                    </div>
                                </a>
                            </div>
                            <h5 style="color: yellow;">Info y data de peliculas</h5>
                            <p class="text-muted" style="color: yellow;">Buscá las peliculas que quieras por nombre,
                                empresa, género o valoración.</p>
                        </div>
                        <div class="col-md-6 box">
                            <div class="icon-box box-danger">
                                <a href="{% url 'Foro' %}">
                                    <div class="icon-box-inner" style="color: yellow;">
                                        <span data-feather="layout" width="35" height="35"></span>
                                    </div>
                                </a>
                            </div>
                            <h5 style="color: yellow;">Foro</h5>
                            <p class="text-muted" style="color: yellow;">Discutí y charla temas variados sobre peliculas
                                en este foro.</p>
                        </div>
                        <div class="col-md-6 box">
                            <div class="icon-box box-info">
                                <a href="{% url 'AppMensajes:Inbox' %}">
                                    <div class="icon-box-inner" style="color: yellow;">
                                        <span data-feather="globe" width="35" height="35"></span>
                                    </div>
                                </a>
                            </div>
                            <h5 style="color: yellow;">Chat con amigos</h5>
                            <p class="text-muted" style="color: yellow;">Chateá con tus amigos por mensajes privados</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-6">
            </div>
        </div>
        </div>
    </section>
    <!--footer-->
    <footer class="py-6">
        <div class="row mt-5" style="color: yellow;">
            <div class="col-12 text-muted text-center small-xl">
                &copy; 2023 Tbb Project for Movies-Ok! - All Rights Reserved
            </div>
        </div>
    </footer>

    <!--scroll to top-->
    <div class="scroll-top">
        <i class="fa fa-angle-up" aria-hidden="true"></i>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>